Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskManagementSystem.Areas.Identity.Data;
using TaskManagementSystem.Models.ViewModels;

namespace TaskManagementSystem.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationContext _context;

        private static readonly List<SelectListItem> _assignableRoles = new()
        {
            new SelectListItem("Developer", "Developer"),
            new SelectListItem("Project Manager", "Project Manager")
        };

        public AdminController(UserManager<ApplicationUser> userManager, ApplicationContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<ApplicationUser> users = new();

            foreach (ApplicationUser user in _userManager.Users)
                if ((await _userManager.GetRolesAsync(user)).Count == 0)
                    users.Add(user);

            return View(new AssignRoleViewModel()
            {
                Users = users,
                Roles = _assignableRoles
            });
        }

        [HttpPost, ActionName("Index")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignRole(string userId, [Bind("Role")] AssignRoleViewModel vm)
        {
            ApplicationUser? user = await _context.Users.FindAsync(userId);

            if (user == null)
                return NotFound();

            if (!(await _userManager.AddToRoleAsync(user, vm.Role)).Succeeded)
                ModelState.AddModelError("", "Could not add user to role.");

            return RedirectToAction("Index");
        }
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.Drawing.Printing;
using System.Transactions;
using TaskManagementSystem.Areas.Identity.Data;
using TaskManagementSystem.Models;
using TaskManagementSystem.Models.ViewModels;

namespace TaskManagementSystem.Controllers
{
    [Authorize(Roles = "Project Manager, Developer")]
    public class ProjectsController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProjectsController(ApplicationContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
            _userManager = userManager;
        }

        // GET: Projects
        public async Task<IActionResult> Index(
            TaskOrderBy orderBy,
            ListSortDirection orderDirection,
            bool showCompleted = true,
            bool showAssigned = true,
            int pageNumber = 1)
        {
            ApplicationUser currentUser = await _userManager.GetUserAsync(User);
            IList<string> roles = await _userManager.GetRolesAsync(currentUser);

            int pageSize = 10;

            ProjectListViewModel vm = new()
            {
                OrderBy = orderBy,
                OrderDirection = orderDirection,
                ShowCompleted = showCompleted,
                ShowAssigned = showAssigned,
                CurrentPage = pageNumber,
            };

            if (await _userManager.IsInRoleAsync(currentUser, "Developer"))
            {
                vm.Projects = _context.Projects
                    .Where(p => p.Developers.Any(pd => pd.ApplicationUserId == currentUser.Id))
                    .Include(p => p.Tasks.Where(t => t.Developers.Any(td => td.ApplicationUserId == currentUser.Id)))
                    .AsEnumerable();
            }
            else
            {
                vm.Projects = _context.Projects
                    .Where(p => p.ApplicationUserId == currentUser.Id)
                    .Include(t => t.Tasks)
                    .ThenInclude(t => t.Developers)
                    .AsEnumerable();
            }

            foreach (ApplicationProject project in vm.Projects)
            {
                IEnumerable<ApplicationTask> tasks = project.Tasks;

                if (!showCompleted)
                {
                    tasks = tasks.Where(t => !t.Completed);
                }

                if (!showAssigned)
                {
                    tasks = tasks.Where(t => !t.Developers.Any());
                }

                switch (orderBy)
                {
                    case TaskOrderBy.RequiredHours:
                        if (orderDirection == ListSortDirection.Ascending)
                        {
                            tasks = tasks.OrderBy(t => t.RequiredHours);
                        }
                        else
                        {
                            tasks = tasks.OrderByDescending(t => t.RequiredHours);
                        }
                        break;
                    case TaskOrderBy.Priority:
                        if (orderDirection == ListSortDirection.Ascending)
                        {
                            tasks = tasks.OrderBy(t => t.Priority);
                        }
                        else
                        {
                            tasks = tasks.OrderByDescending(t => t.Priority);
                        }
                        break;
                };

                project.Tasks = tasks.ToHashSet();
            }

            vm.Projects = vm.Projects.OrderBy(p => p.Title, StringComparer.OrdinalIgnoreCase);

            int totalProjects = vm.Projects.Count();
            int totalPages = (int)Math.Ceiling((decimal)totalProjects / pageSize);
            int skip = (pageNumber - 1) * pageSize;
            vm.Projects = vm.Projects.Skip(skip).Take(pageSize);

            vm.Pagination = new PaginationViewModel()
            {
                TotalPages = totalPages,
                CurrentPage = pageNumber,
                PageSize = pageSize
            };

            return View(vm);
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationProject? projects = await _context.Projects.FindAsync(id);

            if (projects == null)
            {
                return NotFound();
            }

            return View(projects);
        }

        // GET: Projects/Create
        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> Create()
        {
            ApplicationUser projectManager = await _userManager.GetUserAsync(User);
            IList<ApplicationUser> developers = await _userManager.GetUsersInRoleAsync("Developer");

            CreateProjectViewModel vm = new()
            {
                Developers = developers,
                ApplicationUserId = projectManager.Id
            };

            return View(vm);
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> Create(CreateProjectViewModel CreateProject)
        {
            HashSet<ProjectDeveloper> projectDevelopers = new();

            ApplicationProject project = new()
            {
                Title = CreateProject.Title,
                ApplicationUserId = CreateProject.ApplicationUserId
            };

            foreach (string userId in CreateProject.SelectedDevelopersIdList)
            {
                ProjectDeveloper projectDeveloper = new()
                {
                    ApplicationUserId =  userId,
                    ApplicationProjectId = project.Id,
                };

                project.Developers.Add(projectDeveloper);
            }

            _context.Projects.Add(project);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationProject? project = await _context.Projects.FindAsync(id);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] ApplicationProject project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectsExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationProject? project = await _context.Projects.FindAsync(id);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Project Manager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ApplicationProject? projects = await _context.Projects.FindAsync(id);

            if (projects != null)
            {
                _context.Projects.Remove(projects);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectsExists(int id)
        {
          return (_context.Projects?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using TaskManagementSystem.Areas.Identity.Data;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">TaskManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if (SignInManager.IsSignedIn(User))
                            {
                                IList<string> roles = await UserManager.GetRolesAsync(await UserManager.GetUserAsync(User));

                                if (roles.Contains("Developer") || roles.Contains("Project Manager"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-controller="Projects" asp-action="Index">Projects</a>
                                    </li>
                                }
                                else if (roles.Contains("Administrator"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">Assign Roles</a>
                                    </li>
                                }
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TaskManagementSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>